jobs:
  test:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "hashicorp/setup-terraform@v3"
      - uses: "extractions/setup-just@v3"
      - uses: "jaxxstorm/action-install-gh-release@v1.10.0"
        with:
          repo: "marcbran/jsonnet-kit"
      - name: "Run release"
        run: |
          cd terraform
          just release
    timeout-minutes: 5
name: "Test terraform"
"on":
  push:
    tags:
      - "terraform/v*"
permissions:
  contents: "read"