jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "jaxxstorm/action-install-gh-release@v1.10.0"
        with:
          repo: "marcbran/jsonnet-kit"
      - name: "Manifest Jsonnet files"
        run: "jsonnet-kit -J ./terraform-provider/template/vendor manifest \"./terraform-provider/providers/registry.terraform.io/PagerDuty/pagerduty\""
    timeout-minutes: 5
name: "Test registry.terraform.io/PagerDuty/pagerduty"
"on":
  pull_request:
    paths:
      - "terraform-provider/providers/registry.terraform.io/PagerDuty/pagerduty/**"
permissions:
  contents: "read"