jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
      - uses: "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
      - uses: "actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b"
        with:
          cache: true
          go-version-file: "terraform-provider/cmd/pull-provider/go.mod"
      - uses: "jaxxstorm/action-install-gh-release@4304621e8c48d66093a8a214af5d5b5bc3b3d943"
        with:
          repo: "marcbran/jsonnet-kit"
      - name: "Run tests"
        run: |
          cd terraform-provider
          just gen-provider ./providers/registry.terraform.io/hashicorp/kubernetes
    timeout-minutes: 5
name: "Test registry.terraform.io/hashicorp/kubernetes"
"on":
  pull_request:
    paths:
      - "terraform-provider/providers/registry.terraform.io/hashicorp/kubernetes/**"
  workflow_dispatch: {}
permissions:
  contents: "read"