jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
      - uses: "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
      - uses: "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
        with:
          repo: "marcbran/jsonnet-kit"
      - name: "Run tests"
        run: |
          cd terraform
          just test
      - name: "Run integration tests"
        run: |
          cd terraform
          just it
    timeout-minutes: 5
name: "Test terraform"
"on":
  pull_request:
    paths:
      - "terraform/**"
  workflow_dispatch: {}
permissions:
  contents: "read"